settings:
  can_not_member_tp_island: false
  print_prefix: true
  max_players_on_island: 4
messages:
  is:
    not_found: 'У вас нет острова'
    player_not_found: 'Игрок %s не найден'

    # /is
    create_successfully: 'Вы обнаружили необитаемый остров, пропишите /is, чтобы приплыть на него'
    create_failed: 'Произошла ошибка при создании острова...'
    leave: '&4&lВы покинули остров!'

    home: 'Плывём на остров...'

    # /is tp <player>
    tp_successfully: 'Вы приплыли на остров игрока %s'
    tp_failed_island_not_found: 'У игрока %s нет острова'
    tp_failed_player_not_a_member: 'Вы не можете приплыть на остров игрока %s'

    howInvite: 'Чтобы пригласить игрока на остров напишите /is invite <player>'

    event:
      himself: 'Вы не можете отправить приглашение самому себе'
      cancel: 'Запрос отменён'
      no_island: 'У игрока нет острова'

    # /is invite <player>
    invite:
      successfully_inviter: 'Игрок %s присоединился к острову'
      successfully_invited: 'Вы присоединились к острову'
      already_added: 'Игрок %s уже присоединился к вашему острову'
      already_invited: 'Вы уже отправляли приглашение этому игроку, подождите, прежде чем отправить новое'
      already_have_island: 'У вас уже есть остров. Чтобы присоединиться к новому, покиньте текущий'
      send_to_inviter: 'Вы отправили приглашение игроку %s'
      send_to_invited: '%s пригласил вас присоединиться к острову. Напишите /is inviteaccept %s, чтобы присоединиться.'
      inviter_has_island: 'Игрок является членом другого острова'
      not_found: 'Приглашение не найдено'
      too_many_players: 'К вашему острову присоединилось максимальное количество игроков'

    visit:
      send_to_visitor: 'Вы отправили запрос на посещение острова игрока %s'
      send_to_visited: 'Ваш остров хочет посетить %s. Напишите /is visitaccept %s, чтобы принять.'
      successfully_visitor: 'Вы прибыли на остров игрока %s'
      successfully_visited: 'Приглашение принято'
      not_allowed: 'На остров этого игрока нельзя телепортироваться'
      not_found: 'Запрос не найден'


  # console
  sender_not_a_player: 'Прости, консолька :('
  # Префикс в чате, при вызове команд
  chat_prefix: '&b&l[MinimalSkyblock]&f&r '
inv:
  create_island:
    name: '&6&lСОЗДАТЬ ОСТРОВ'
    lore:
      - '&7Начните своё выживание на острове'
  go_island:
    name: '&2&lНА ОСТРОВ'
    lore:
      - '&7Телепортирует Вас на остров'
  pvp:
    enable: '&4&lPVP НА ОСТРОВЕ ВКЛЮЧЕНО'
    disable: '&2&lPVP НА ОСТРОВЕ ВЫКЛЮЧЕНО'
    lore:
      - '&7Вы можете включать и выключать PVP на острове'
  set_spawn:
    name: '&6&lУСТАНОВИТЬ НОВУЮ ТОЧКУ СПАВНА ОСТРОВА'
    lore:
      - '&6Новым местом спавна будет ваша текущая позиция'
  members:
    name: '&3&lДОБАВИТЬ ИГРОКОВ НА СВОЙ ОСТРОВ'
    max: '&7Вы можете добавить до {count} игроков'
    no_members: '&7К вам никто ещё не присоединился'
    have_members: '&7К вашему острову присоединились:'
  visits:
    name: '&3&lВАШ ОСТРОВ МОЖНО ПОСЕТИТЬ:'
    anybody: 'Любому игроку'
    by_invitation: 'Только по приглашению'
    nobody: 'Никому'
  leave_island:
    name: '&4&lПОКИНУТЬ ОСТРОВ'
    lore:
      - '&4Вы не сможете телепортироваться на'
      -  '&4этот остров, а ваши вещи удалятся'
    cancel:
      name: '&7&lОТМЕНИТЬ'
      lore:
        - '&7Отменить уход с острова'
islands:
  # Мир, в котором генерируются острова
  world: 'world'
  # Имя файла схематики, который будет генерироваться, без расширения
  name_schematic_file: 'default'
  # Размер острова по X в блоках
  size_x: 50
  # Размер острова по Y в блоках
  size_z: 50
  # Высота генерации острова
  height: 100
  # Расстояние между островов, на котором никто не может строить
  distance_between: 10
  # Координаты телепортации игрока, относительно начальной точки острова
  teleport_deviation:
    x: 2
    y: 2
    z: 1
# Don't change it
version: @pluginVersion@

