messages:
  # /is invite <player>
  invite_successfully: 'Игрок %s добавлен'
  invite_player_not_found: 'Игрок не найден'
  invite_already_added: 'Игрок уже присоединился к вашему острову'
  # /is
  is_create_island: 'Вы обнаружили необитаемый остров, пропишите /is, чтобы приплыть на него'
  is_home: 'Плывём на остров...'
  sender_not_a_player: 'Прости, консолька :('
islands:
  # Мир, в котором генерируются острова
  world: 'world'
  #'okeanworld'
  # Имя файла схематики, который будет генерироваться, без расширения
  name_schematic_file: 'default'
  # Размер острова по X в блоках
  size_x: 50
  # Размер острова по Y в блоках
  size_z: 50
  # Высота генерации острова
  height: 100
  #62
  # Расстояние между островов, на котором никто не может строить
  distance_between: 10
  # Координаты телепортации игрока, относительно начальной точки острова
  teleport_deviation:
    x: 2
    y: 2
    z: 1
version: @version@

