settings:
  can_not_member_tp_island: false
  print_prefix: true
messages:
  is_not_found: 'У вас нет острова'
  is_player_not_found: 'Игрок %s не найден'
  # /is
  is_create_successfully: 'Вы обнаружили необитаемый остров, пропишите /is, чтобы приплыть на него'
  is_create_failed: 'Произошла ошибка при создании острова...'
  is_home: 'Плывём на остров...'
  # /is tp <player>
  is_tp_successfully: 'Вы приплыли на остров игрока %s'
  is_tp_failed_island_not_found: 'У игрока %s нет острова'
  is_tp_failed_player_not_a_member: 'Вы не можете приплыть на остров игрока %s'
  # /is allowvisits <boolean>
  is_allowvisits_true: 'Теперь любые игроки могут посетить ваш остров'
  is_allowvisits_false: 'Теперь только члены острова могут его посетить'
  # /is join <player>
  is_join_successfully: 'Игрок %s присоединился к острову'
  is_join_yourself: 'Вы не можете сделать себя членом острова, так как являетесь его лидером'
  is_join_already_added: 'Игрок %s уже присоединился к вашему острову'
  # /is kick <player>
  is_kick_successfully: 'Игрок %s исключён с острова'
  is_kick_yourself: 'Вы не можете исключить себя с острова, так как являетесь его лидером'
  is_kick_player_not_added: 'Игрок %s не является членом острова'
  # console
  sender_not_a_player: 'Прости, консолька :('
  # Префикс в чате, при вызове команд
  chat_prefix: '&b&l[MinimalSkyblock]&f&r '
islands:
  # Мир, в котором генерируются острова
  world: 'world'
  #'okeanworld'
  # Имя файла схематики, который будет генерироваться, без расширения
  name_schematic_file: 'default'
  # Размер острова по X в блоках
  size_x: 50
  # Размер острова по Y в блоках
  size_z: 50
  # Высота генерации острова
  height: 100
  #62
  # Расстояние между островов, на котором никто не может строить
  distance_between: 10
  # Координаты телепортации игрока, относительно начальной точки острова
  teleport_deviation:
    x: 2
    y: 2
    z: 1
# Don't change it
version: @pluginVersion@

