name: UCrafterIslands
version: @version@
main: ru.ucrafter.plugins.ucrafterislands.UCrafterIslands
authors: [Totalexx]
depend: [WorldGuard, WorldEdit]

commands:
  is:
    description: Создаёт новый остров или телепортирует на существующий
    usage: /is
    permission: ucrafter.island
  is invite:
    description: Отправляет приглашение игроку присоедениться к вашему острову
    usage: /is invite <player>
    permission: ucrafter.island
